# Tensor Operations

PyTorch is a powerful Machine Learning Library that is easy to work with for passion projects and building prototypes.
- torch.linspace
- torch.eye
- torch.full
- torch.take
- torch.tensor.clone

In [57]:
# Import torch and other required modules
import torch

## Function 1 - torch.linspace

It gives a 1-D tensor with evenly spaced numbers between the two specified arguments(input numbers), By default it gives tensor with a length of 100.

In [58]:
# Example 1 - torch.linspace
torch.linspace(2,3)
#len(torch.linspace(2,3))  >> 100

tensor([2.0000, 2.0101, 2.0202, 2.0303, 2.0404, 2.0505, 2.0606, 2.0707, 2.0808,
        2.0909, 2.1010, 2.1111, 2.1212, 2.1313, 2.1414, 2.1515, 2.1616, 2.1717,
        2.1818, 2.1919, 2.2020, 2.2121, 2.2222, 2.2323, 2.2424, 2.2525, 2.2626,
        2.2727, 2.2828, 2.2929, 2.3030, 2.3131, 2.3232, 2.3333, 2.3434, 2.3535,
        2.3636, 2.3737, 2.3838, 2.3939, 2.4040, 2.4141, 2.4242, 2.4343, 2.4444,
        2.4545, 2.4646, 2.4747, 2.4848, 2.4949, 2.5051, 2.5152, 2.5253, 2.5354,
        2.5455, 2.5556, 2.5657, 2.5758, 2.5859, 2.5960, 2.6061, 2.6162, 2.6263,
        2.6364, 2.6465, 2.6566, 2.6667, 2.6768, 2.6869, 2.6970, 2.7071, 2.7172,
        2.7273, 2.7374, 2.7475, 2.7576, 2.7677, 2.7778, 2.7879, 2.7980, 2.8081,
        2.8182, 2.8283, 2.8384, 2.8485, 2.8586, 2.8687, 2.8788, 2.8889, 2.8990,
        2.9091, 2.9192, 2.9293, 2.9394, 2.9495, 2.9596, 2.9697, 2.9798, 2.9899,
        3.0000])

In [59]:
torch.linspace(2,3,steps=10)

tensor([2.0000, 2.1111, 2.2222, 2.3333, 2.4444, 2.5556, 2.6667, 2.7778, 2.8889,
        3.0000])

You can change the length of the output tensor by changing the default steps argument.

In [61]:
# Example 3 - Breaking
torch.linspace(2,steps=19)


TypeError: linspace() missing 1 required positional arguments: "end"

It's a useful function when you want to limit your output in a certain range, ANd it comes quite handy with specifying number of outputs.

## Function 2 - torch.eye

It's an operation returns a 2D-matrix with diagonal ones and the other elements zeroes, By passing the the number of rows and coloumns desired.


In [14]:
# Example 1 - working
torch.eye(4,5)


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [ ]:
# Example 2 - working
torch.eye(3)

If you pass one argument will make it an squared matrix.

In [63]:
# Example 3 - breaking (to illustrate when it breaks)
#x=torch.tensor([3,4]) >> you must create a tensor then pass it or it'll treat it like a list.
torch.eye(2,4,out=[3,4])

TypeError: eye() received an invalid combination of arguments - got (int, int, out=list), but expected one of:
 * (int n, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int n, int m, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


It's a function that return an identity functuin(if passed one argument) and quite useful one you don't want to change your input function.

## Function 3 - tensor.full

It returns a matrix filled with the value you desired with a certain size passed.

In [64]:
# Example 1 - working
torch.full(size=(2,3,4) , fill_value=9)

tensor([[[9., 9., 9., 9.],
         [9., 9., 9., 9.],
         [9., 9., 9., 9.]],

        [[9., 9., 9., 9.],
         [9., 9., 9., 9.],
         [9., 9., 9., 9.]]])

In [65]:
# Example 2 - working 
torch.full(size=[2,3,4], fill_value=9)

tensor([[[9., 9., 9., 9.],
         [9., 9., 9., 9.],
         [9., 9., 9., 9.]],

        [[9., 9., 9., 9.],
         [9., 9., 9., 9.],
         [9., 9., 9., 9.]]])

You pass size as list instead of a tuple.

In [66]:
# Example 3 - breaking (to illustrate when it breaks)
torch.full([1,2],9)

tensor([[9., 9.]])

You should pass the size (as tuple or list) with 2 parameteres even if you want it as one dimentional tensor

It comes quite handy when you want a matrix filled with specific number not anything else.


## Function 4 - torch.take

It returns a tensor with the desired element ( passing the indices associated within the function), of the input tensor

In [67]:
# Example 1 - working
x = torch.tensor([3,5,6,7,3])
torch.take(x, torch.tensor([4]))

tensor([3])

It returned the 5th element as a tensor.

In [68]:
# Example 2 - working
x = torch.tensor([[9,7,3],
                  [8,5,6]])
torch.take(x, torch.tensor([3,4]))

tensor([8, 5])

Even with 2-D tensors it return the elements with just their indices if followed one by one.

In [69]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([[9,7,3],
                  [8,5,6]])
torch.take(x, torch.tensor([3,7]))

RuntimeError: invalid argument 2: out of range: 7 out of 6 at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:314

It won't work if even one of the passed indices is out of range , Other than That it's straight forward.

It comes handy with slicing or selecting certain elements of a tensor and returning it as a tensor.

## Function 5 - torch.tensor.clone

It returns a copy of a tensor with the same size and data type.

In [70]:
# Example 1 - working
x=torch.tensor([[2,3],[4,5]])
y=x.clone()
y

tensor([[2, 3],
        [4, 5]])

Returns the copied tensor.

In [71]:
# Example 2 - working
x=torch.tensor([[2,3],[4,5]])
y=x.clone()
x[1,1]=9
y

tensor([[2, 3],
        [4, 5]])

we should pay attention to the fact that altering the original matrix won't affect the coped one after using.clone()

In [72]:
# Example 3 - breaking (to illustrate when it breaks)
x=torch.tensor([[2,3],[4,5]])
y=x.clone()
y[2,1]=9


IndexError: index 2 is out of bounds for dimension 0 with size 2

Altering copied tensor should be with the same bounds the the original one.

It comes handy when you want to make a copy of a tensor and making sure that altering any of the tensors won't affect the other one.

## Conclusion

We covered an interesting tensors operations that heps with many operations required for your projects. Always check the official documentation for any further details.

## Reference Links
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html


In [73]:
!pip install jovian --upgrade --quiet

In [74]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>